version: "3.12"

services:
  db:
    container_name: postgres-db
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:latest

  web:
    image: url_shortener_py:latest
    depends_on:
      - db
      - cache
    environment:
      DATABASE_URL: "postgresql://test:password@db/postgres"
      REDIS_URL: "redis://cache:6379/0"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
